name: Install Macaulay2 on Release

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Homebrew
      run: |
        # Install Homebrew if not already installed
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Tap Macaulay2 Homebrew
      run: |
        brew tap Macaulay2/homebrew-tap

    - name: Install Macaulay2
      run: |
        brew install macaulay2

    - name: Ensure macaulay2 is in PATH
      run: |
        # Ensure that Homebrew's binary directory is in the PATH
        echo "$(brew --prefix)/bin" >> $GITHUB_PATH
        echo "Macaulay2 binary path added to PATH: $(brew --prefix)/bin"

    - name: Verify Macaulay2 installation
      run: |
        macaulay2 --version

    - name: Find Macaulay2 binary
      id: find_binary
      run: |
        # Find where the Macaulay2 binary was installed by Homebrew
        MACAULAY2_BIN_PATH=$(which macaulay2)
        echo "MACAULAY2_BIN_PATH=${MACAULAY2_BIN_PATH}" >> $GITHUB_ENV
        echo "Macaulay2 binary found at: $MACAULAY2_BIN_PATH"

    - name: Upload Macaulay2 Binary as Artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: macaulay2-binary
        path: ${{ env.MACAULAY2_BIN_PATH }}
