name: Install Macaulay2 on Release

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Homebrew
      run: |
        # Install Homebrew if not already installed
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Tap Macaulay2 Homebrew
      run: |
        brew tap Macaulay2/tap  # Correct tap for Macaulay2

    - name: Install M2
      run: |
        brew install M2  # Install the M2 binary and all dependencies

    - name: Identify M2 Installation Location
      id: find_m2_prefix
      run: |
        # Find where Homebrew has installed M2
        M2_PREFIX=$(brew --prefix M2)
        echo "M2_PREFIX=${M2_PREFIX}" >> $GITHUB_ENV
        echo "M2 installed at: ${M2_PREFIX}"

    - name: Upload M2 and All Dependencies as Artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: m2-homebrew-package
        path: ${{ env.M2_PREFIX }}  # Upload the entire directory where M2 is installed
